updated deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -33,7 +33,7 @@ jobs:
         run: npm ci
 
       - name: Build React app
-        run: npm run build
+        run: npm run build --if-present || (echo "Build failed" && exit 1)
 
       - name: Setup GitHub Pages
         uses: actions/configure-pages@v5
@@ -46,3 +46,9 @@ jobs:
       - name: Deploy to GitHub Pages
         id: deployment
         uses: actions/deploy-pages@v4
+      
+      - name: Show build log
+        if: failure()
+        run: |
+          echo "Dumping npm debug log if it exists..."
+          cat npm-debug.log || echo "Np npm-debug.log found"
